2020-09-29 15:09:40.930 ERROR [http-nio-9001-exec-9] xyz.zjhwork.conf.exceptionhandler.SystemExceptionHandler.handleValidException():27 - 1111111111111111111111
2020-09-29 15:12:29.657 ERROR [http-nio-9001-exec-5] xyz.zjhwork.conf.exceptionhandler.SystemExceptionHandler.handleValidException():29 - 系统出现异常：1111111111111111111111
2020-09-29 15:42:52.857 ERROR [http-nio-9001-exec-3] xyz.zjhwork.conf.exceptionhandler.SystemExceptionHandler.handleValidException():31 - 系统出现异常：测试主动抛出异常！
2020-09-29 15:44:44.720 ERROR [http-nio-9001-exec-7] xyz.zjhwork.conf.exceptionhandler.SystemExceptionHandler.handleValidException():31 - 系统出现异常：测试主动抛出异常！
2020-09-29 15:45:07.090 ERROR [http-nio-9001-exec-8] xyz.zjhwork.conf.exceptionhandler.SystemExceptionHandler.handleValidException():31 - 系统出现异常：测试主动抛出异常！
2020-09-29 15:49:11.846 ERROR [http-nio-9001-exec-10] xyz.zjhwork.conf.exceptionhandler.SystemExceptionHandler.handleValidException():31 - 系统出现异常：测试主动抛出异常2
